MODEL:
  TYPE: MaxViT
  NAME: max_vit_base_224
  DROP_PATH_RATE: 0.4
  NUM_CLASSES: 1000
  MAX_VIT:
    EMBED_DIM: 64
    DEPTHS: [2, 6, 14, 2]
    DIM_HEAD: 32
    WINDOW_SIZE: [7, 7]
    POOL: "avg"
    CHANNELS: (96, 192, 384, 768)
