MODEL:
  TYPE: MaxViT
  NAME: max_vit_large_224
  DROP_PATH_RATE: 0.6
  NUM_CLASSES: 1000
  MAX_VIT:
    EMBED_DIM: 128
    DEPTHS: [2, 6, 14, 2]
    DIM_HEAD: 32
    WINDOW_SIZE: [7, 7]
    POOL: "avg"
    CHANNELS: (128, 256, 512, 1024)